# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.network "forwarded_port", guest: 22, host: 2222,
        auto_correct: true
    config.vm.box = "jeff/devbox"
	config.vm.provider :virtualbox do |p|
		p.customize ["modifyvm", :id, "--memory", 2048]
		p.customize ["modifyvm", :id, "--cpus", 2]
		p.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
	end
    config.ssh.private_key_path = ENV['HOME'] + "/.ssh/vagrant_rsa"
    config.ssh.username = "vagrant"
	config.vm.hostname = "centos7-devbox0000"
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = ENV['HOME'] + "/dev/packer/ansible/vagrant_devbox.yml"
		ansible.host_key_checking = false
		ansible.raw_ssh_args = '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no'
	end
end
