---
# vars file for python3

py_ver: 3.6.3
py_ver_short: 3.6
py_md5: e9180c69ed9a878a4a8a3ab221e32fa9
pip_pkgs:
  - boto3
  - awscli
  - jupyter
  - plotly
  - setuptools
  - virtualenv
  - pandas
  - numpy
  - matplotlib
  - Sphinx
